mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
import django.contrib.auth.views
from django.urls import path, re_path, include
import restaurants.views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', restaurants.views.menu),
    #re_path(r'menu/(\d{1,5})', restaurants.views.menu),
    re_path(r'menu/(?P<pk>\d+)', restaurants.views.MenuView.as_view()),
    path('meta/', restaurants.views.meta),
    path('welcome/', restaurants.views.welcome),
    path('index/', TemplateView.as_view(template_name='index.html')),
    path('accounts/login/', django.contrib.auth.views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/profile/', TemplateView.as_view(template_name='index.html')),
    path('accounts/register/', restaurants.views.register),
    #re_path(r'comment/(?P<id>\d{1,5})', restaurants.views.comment),
    re_path(r'comment/(?P<pk>\d+)', restaurants.views.CommentView.as_view()),
    path('firstmenu/', restaurants.views.menu),
    path('restaurants_list/', django.contrib.auth.views.login_required(
        restaurants.views.RestaurantsView.as_view(), {'model': restaurants.models.Restaurant})),
    path('users_list/', restaurants.views.list,
         {'model': django.contrib.auth.models.User}),
    path('test/', restaurants.views.test),
    path(r'', TemplateView.as_view(template_name='index.html')),
]
if settings.DEBUG:
    urlpatterns += [
        path('test/', restaurants.views.test),
    ]
    """path('restaurants_list/', django.contrib.auth.views.login_required(
        restaurants.views.list, {'model': restaurants.models.Restaurant}))"""
    """path('restaurants_list/', restaurants.views.list,
            {'model': restaurants.models.Restaurant}),"""


mysite/restaurants/models.py
from django.db import models, connection


class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15, verbose_name='foneNum')
    address = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name


class FoodManager(models.Manager):
    def sfood_order_by_price(self):
        return self.filter(is_spicy=True).order_by('price')

    def sfood(self):
        return self.filter(is_spicy=True)

    def cheap_food_num(self):
        return self.filter(price__lt=100).count()

    def get_120_food(self):
        cursor = connection.cursor()
        cursor.execute("""
            SELECT name
            FROM restaurants_food
            WHERE price=120
        """)
        return [result[0] for result in cursor.fetchall()]


class NotSpicyFoodManager(models.Manager):
    def get_queryset(self):
        return super(NotSpicyFoodManager, self).get_queryset().filter(is_spicy=False)


class SpicyFoodManager(models.Manager):
    def get_queryset(self):
        return super(SpicyFoodManager, self).get_queryset().filter(is_spicy=True)


class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    objects = FoodManager()
    Sobjects = SpicyFoodManager()
    NSobjects = NotSpicyFoodManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['price']


class Author(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)


class Comment(models.Model):
    content = models.CharField(max_length=200)
    visitor = models.CharField(max_length=20)
    email = models.EmailField(max_length=20)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    class Meta:
        ordering = ['date_time']
        permissions = (
            ("can_comment", "Can comment"),
        )


class Account(models.Model):
    money = models.IntegerField()

mysite/restaurants/forms.py
from django import forms


class CommentForm(forms.Form):
    visitor = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20, required=False, label='E-mail')
    content = forms.CharField(max_length=200, widget=forms.Textarea())

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) < 5:
            raise forms.ValidationError('字數不足')
        return content

mysite/restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.views.generic.base import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView
from restaurants.models import Restaurant, Food, Comment
from restaurants.forms import CommentForm


class IndexView(TemplateView):
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['request'] = request
        return self.render(request, context)

    def get_context_data(self, **kwargs):
        # 取得字典型態的Context
        context = super(IndexView, self).get_context_data(**kwargs)
        # 加入我們額外想要的時間參數
        context["time"] = timezone.now()
        return context


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', locals())


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/index/')
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/index/')
    else:
        return render(request, 'login.html', locals())


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/index/')


def user_can_comment(user):
    return user.is_authenticated and user.has_perm('restaurants.can_comment')


class CommentView(FormView, SingleObjectMixin):
    form_class = CommentForm
    template_name = 'comments.html'
    success_url = '/comment/'
    initial = {'content': '我沒意見'}
    model = Restaurant
    context_object_name = 'r'

    def form_valid(self, form):
        Comment.objects.create(
            visitor=form.cleaned_data['visitor'],
            email=form.cleaned_data['email'],
            content=form.cleaned_data['content'],
            date_time=timezone.localtime(timezone.now()),
            restaurant=self.get_object(),
        )
        return self.render(request, self.get_context_data(
            form=self.form_class(initial=self.initial)
        ))

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        return super(CommentView, self).get_context_data(object=self.object, **kwargs)
        # return super(CommentView, self).form_valid(form)

    @method_decorator(user_passes_test(user_can_comment, login_url='/accounts/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(CommentView, self).dispatch(request, *args, **kwargs)


@permission_required('restaurants.can_comment', login_url='/accounts/login/')
def comment(request, id):
    if request.user.is_authenticated and request.user.has_perm('restaurants.can_comment'):
        if id:
            r = Restaurant.objects.get(id=id)
        else:
            return HttpResponseRedirect("/restaurants_list/")
        if request.POST:
            f = CommentForm(request.POST)
            if f.is_valid():
                visitor = f.cleaned_data['visitor']
                content = f.cleaned_data['content']
                email = f.cleaned_data['email']
                date_time = timezone.localtime(timezone.now())  # 擷取現在時間
                Comment.objects.create(
                    visitor=visitor, email=email, content=content, date_time=date_time, restaurant=r)
                visitor, content, email = ('', '', '')
                f = CommentForm(initial={'content': '我沒意見'})
        else:
            f = CommentForm(initial={'content': '我沒意見'})
        return render(request, 'comments.html', locals())
    else:
        return HttpReponseRedirect('/restaurants_list/')


class MenuView(DetailView):
    model = Restaurant
    template_name = 'menu.html'
    context_object_name = 'restaurant'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MenuView, self).dispatch(request, *args, **kwargs)

    def get(self, request, pk, *args, **kwargs):
        try:
            return super(MenuView, self).get(self, request, pk=pk, *args, **kwargs)
        except Http404:
            return HttpResponseRedirect('/restaurants_list/')


def menu(request, id=1):
    if id:
        restaurant = Restaurant.objects.get(id=id)
        return render(request, 'menu.html', locals())
    else:
        return HttpResponseRedirect("/restaurants_list/")


def meta(request):
    values = request.META.items()
    html = []
    for k, v in values:
        html.append('<tr><td>{0}</td><td>{1}</td></tr>'.format(k, v))
    return HttpResponse('<table>{0}</table>'.format('\n'.join(html)))


'''def menu(request, id):
    if id:
        restaurant = Restaurant.objects.get(id=id)
        return render(request, 'menu.html', locals())
    else:
        return HttpResponseRedirect("/restaurants_list/")
'''


def welcome(request):
    if 'user_name' in request.GET and request.GET['user_name'] != '':
        return HttpResponse('Welcome!~' + request.GET['user_name'])
    else:
        return render(request, 'welcome.html', locals())


def set_c(request):
    response = HttpResponse('Set your lucky_number as 8')
    response.set_cookie('lucky_number', 8)
    return response


def get_c(request):
    if 'lucky_number' in request.COOKIES:
        return HttpResponse('Your lucky_number is {0}'.format(request.COOKIES['lucky_number']))
    else:
        return HttpResponse('No cookies.')


def use_session(request):
    request.session['lucky_number'] = 8  # 設置lucky_number
    if 'lucky_number' in request.session:
        lucky_number = request.session['lucky_number']  # 讀取lucky_number
        response = HttpResponse('Your lucky_number is ' + str(lucky_number))
    return response


def session_test(request):
    sid = request.COOKIES['sessionid']
    sid2 = request.session.session_key
    s = Session.objects.get(pk=sid)
    s_info = 'Session ID:' + sid + '<br>SessionID2:' + sid2 + \
        '<br>Expire_date:' + str(s.expire_date) + \
        '<br>Data:' + str(s.get_decoded())
    return HttpResponse(s_info)


class RestaurantsView(ListView):
    model = Restaurant
    template_name = 'restaurants_list.html'
    context_object_name = 'restaurants'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(RestaurantsView, self).dispatch(request, *args, **kwargs)


def list_restaurants(request):
    """if not request.user.is_authenticated:
        return rende(request,'error.html')"""
    """request.session['restaurants'] = restaurants"""
    restaurants = Restaurant.objects.all()
    print(request.user.user_permissions.all())
    return render(request, 'restaurants_list.html', locals())


def list_users(request):
    users = auth.models.User.objects.all()
    return render(request, 'users_list.html', locals())


@login_required
def list(request, model):
    objs = model.objects.all()
    return render(request, '{0}s_list.html'.format(model.__name__.lower()), locals())


def test(request):
    return render(request, 'test.html', locals())


class AdvTemplateView(TemplateView):

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.context)


class MyView(AdvTemplateView):
    template_name = 'index.html'
    # 利用一個tricky的技巧取得context
    context = AdvTemplateView().get_context_data()
    context['hello'] = '123'  # 提供了hello變量

mysite/restaurants/templates/comments.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <style>
            .errorlist{
                color: red;
            }
        </style>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.visitor }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}
        <br/><br/>
        {% if f.errors %}
        <p style="color:red;">
            請依提示修復表單錯誤
        </p>
        {% endif %}
        <form action="" method="post"> {% csrf_token %}
            <table>
                <tr>
                    <th> <label for="id_visitor">留言者:</label> </th>
                    <td> {{ form.visitor }} </td>
                    <td> {{ form.visitor.errors }} </td>
                </tr>
                <tr>
                    <th> <label for="id_email">電子信箱:</label> </th>
                    <td> {{ form.email }} </td>
                    <td> {{ form.email.errors }} </td>
                </tr>
                <tr>
                    <th> <label for="id_content">評價:</label> </th>
                    <td> {{ form.content }} </td>
                    <td> {{ form.content.errors }} </td>
                </tr>
            </table>
            <input type="submit" value="給予評價">
        </form>
    </body>
</html>

mysite/restaurants/templates/menu.html
{% load myfilters %}
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='UTF-8'>
        <style>
            table, th, td{
                border: 1px solid black;
            }
        </style>
    </head>
    <body>
        <h2>{{ restaurant.name }}的Menu</h2>
        {% if restaurant.food_set.all %}
            <p>本餐廳共有{{ restaurant.food_set.all|length }}道菜</p>
            <table>
                <tr>
                    <th>菜名</th>
                    <th>價格</th>
                    <th>註解</th>
                    <th>辣不辣</th>
                </tr>
            {% for food in restaurant.food_set.all %}
                <tr>
                    <td> {{ food.name }} </td>
                    <td> {{ food.price }} </td>
                    <td> {{ food.comment }} </td>
                    <td> {{ food.is_spicy|yes_no:"辣/不辣" }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>本餐廳啥都沒賣</p>
        {% endif %}
    </body>
</html>

mysite/restaurants/templates/restaurants_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Restaurants </title>
        <style>
            table, th, td{
                border: 1px solid black;
            }
        </style>
    </head>
    <body>
        <h2>餐廳列表</h2>
        <form action="/menu/" method="get">
        <table>
            <tr>
                <th>選取</th>
                <th>店名</th>
                <th>電話</th>
                <th>地址</th>
                {% if perms.restaurants.can_comment %}
                    <th>評價</th>
                {% endif %}
            </tr>
            {% for r in restaurants%}
                <tr>
                    <td> <input type="radio" name="id" value="{{r.id}}"> </td>
                    <td> <a href="/menu/{{r.id}}"> {{r.name}} </a></td>
                    <td> {{ r.phone_number }} </td>
                    <td> {{ r.address }} </td>
                    {% if perms.restaurants.can_comment %}
                        <td> <a href="/comment/{{r.id}}/"> comment </a> </td>
                    {% endif %}
                    <!--<td> <a href="/menu/{{r.id}}"> menu </a></td>-->
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="觀看菜單">
        </form>
    </body>
</html>

mysite/restaurants/templates/users_list.html
{% extends 'base.html' %}
{% block title %} 使用者列表 {% endblock %}
{% block content %}
    <table>
        <tr>
            <th>使用者帳號</th>
            <th>使用者姓名</th>
        </tr>
        {% for u in objs %}
        <tr>
            <td>{{u.username}}</td>
            <td>{{u.last_name}}{{u.first_name}}</td>
        </tr>
        {% endfor %}
    <table>
{% endblock %}